#----------------------------------------------------------------------------
#       Make Workspace
#
# $Id: MakeWorkspaceCreator.pm 2191 2014-03-05 22:06:46Z mitza $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /Volumes/researchCodes/pinExperiment/MPC/mwc.pl -type make probabilistic_miner.mwc
#
#----------------------------------------------------------------------------


all: probabilistic_miner

depend: probabilistic_miner-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.probabilistic_miner $(@)

.PHONY: probabilistic_miner
probabilistic_miner:
	@$(MAKE) -f Makefile.probabilistic_miner all

.PHONY: probabilistic_miner-depend
probabilistic_miner-depend:
	@$(MAKE) -f Makefile.probabilistic_miner depend

project_name_list:
	@echo probabilistic_miner
